In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv(r'C:\Users\Marco\Documents\CIND 119\Final Project\Project datasets\project_datasets\customer_churn\churn.csv')
df.head(5)

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Mins  Day Calls  Day Charge  ...  Eve Calls  Eve Charge  \
0             25     265.1        110       45.07  ...         99       16.78   
1             26     161.6        123       27.47  ...        103       16.62   
2              0     243.4        114       41.38  ...        110       10.30   
3              0     299.4         71       50.90  ...         88        5.26   
4              0     166.7        113       28.34  ...        122       12.61   

   Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0       244.7           91         11.01       10.0           3         2.70   
1       254.4          103         11.45       13.7           3         3.70   
2       162.6          104          7.32       12.2           5         3.29   
3       196.9           89          8.86        6.6           7         1.78   
4       186.9          121          8.41       10.1           3         2.73   

   CustServ Calls  Churn?  
0               1  False.  
1               1  False.  
2               0  False.  
3               2  False.  
4               3  False.  

[5 rows x 21 columns]

In [3]:
df.shape

(3333, 21)

In [4]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder()

df['State'] = label_encoder.fit_transform(df['State'])
df['Phone'] = label_encoder.fit_transform(df['Phone'])
df["Int'l Plan"] = label_encoder.fit_transform(df["Int'l Plan"])
df['VMail Plan'] = label_encoder.fit_transform(df['VMail Plan'])

print(df.dtypes)

State               int32
Account Length      int64
Area Code           int64
Phone               int32
Int'l Plan          int32
VMail Plan          int32
VMail Message       int64
Day Mins          float64
Day Calls           int64
Day Charge        float64
Eve Mins          float64
Eve Calls           int64
Eve Charge        float64
Night Mins        float64
Night Calls         int64
Night Charge      float64
Intl Mins         float64
Intl Calls          int64
Intl Charge       float64
CustServ Calls      int64
Churn?             object
dtype: object


In [5]:
dependent = df.loc[:,df.columns != 'Churn?']

In [6]:
independent = df['Churn?']

In [7]:
independent = independent.replace({'False.':0,'True.':1})

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(dependent,independent,test_size=0.20,random_state=5)

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

In [10]:
dtree=DecisionTreeClassifier(criterion = "gini",random_state = 25)
dtree.fit(x_train,y_train)

dt_pred = dtree.predict(x_test)

dt_accuracy = round(metrics.accuracy_score(y_test,dt_pred)*100,2)
dt_accuracy

92.65

In [11]:
print(metrics.classification_report(y_test,dt_pred))
print(confusion_matrix(y_test,dt_pred))

              precision    recall  f1-score   support

           0       0.97      0.94      0.96       575
           1       0.70      0.82      0.75        92

    accuracy                           0.93       667
   macro avg       0.84      0.88      0.86       667
weighted avg       0.93      0.93      0.93       667

[[543  32]
 [ 17  75]]


In [12]:
NBG = GaussianNB()
NBG.fit(x_train,y_train)

NB_pred=NBG.predict(x_test)
NB_accuracy=round(metrics.accuracy_score(y_test,NB_pred)*100,2)
NB_accuracy

88.76

In [13]:
print(metrics.classification_report(y_test,NB_pred))
print(confusion_matrix(y_test,NB_pred))

              precision    recall  f1-score   support

           0       0.93      0.94      0.93       575
           1       0.60      0.58      0.59        92

    accuracy                           0.89       667
   macro avg       0.76      0.76      0.76       667
weighted avg       0.89      0.89      0.89       667

[[539  36]
 [ 39  53]]


In [14]:
logreg = LogisticRegression(random_state=50)
logreg.fit(x_train,y_train)

log_pred = logreg.predict(x_test)

logreg_accuracy=round(metrics.accuracy_score(y_test,log_pred)*100,2)
logreg_accuracy

C:\Users\Marco\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


86.36

In [15]:
print(metrics.classification_report(y_test,log_pred))
print(confusion_matrix(y_test,log_pred))

              precision    recall  f1-score   support

           0       0.86      1.00      0.93       575
           1       1.00      0.01      0.02        92

    accuracy                           0.86       667
   macro avg       0.93      0.51      0.47       667
weighted avg       0.88      0.86      0.80       667

[[575   0]
 [ 91   1]]
